import fetch from 'node-fetch';
import fs from 'fs';
import path from 'path';
import { GroqAnalysisResult } from './groqService';

interface JiraSettings {
    projectName: string;
    jiraEmail: string;
    jiraApiKey: string;
    jiraUrl: string;
    issueType: string;
}

function getAuthHeader(email: string, apiToken: string): string {
    return 'Basic ' + Buffer.from(`${email}:${apiToken}`).toString('base64');
}

function normalizeJiraUrl(url: string): string {
    let normalized = url.trim();
    if (!normalized.startsWith('http://') && !normalized.startsWith('https://')) {
        normalized = 'https://' + normalized;
    }
    if (normalized.endsWith('/')) {
        normalized = normalized.slice(0, -1);
    }
    return normalized;
}

export async function createJiraIssue(
    settings: JiraSettings,
    analysis: GroqAnalysisResult,
    userNotes: string
): Promise<{ success: boolean; issueKey?: string; issueUrl?: string; message: string }> {
    const baseUrl = normalizeJiraUrl(settings.jiraUrl);
    const auth = getAuthHeader(settings.jiraEmail, settings.jiraApiKey);

    const description = `h2. Bug Description
${analysis.description}

h2. Steps to Reproduce
${analysis.stepsToReproduce}

h2. Expected Behavior
${analysis.expectedBehavior}

h2. Actual Behavior
${analysis.actualBehavior}

${userNotes ? `h2. Additional Notes\n${userNotes}` : ''}

----
_This bug report was auto-generated by Bug Report Enhancer using AI analysis._`;

    try {
        const response = await fetch(`${baseUrl}/rest/api/2/issue`, {
            method: 'POST',
            headers: {
                'Authorization': auth,
                'Content-Type': 'application/json',
                'Accept': 'application/json',
            },
            body: JSON.stringify({
                fields: {
                    project: { key: settings.projectName },
                    summary: analysis.title,
                    description: description,
                    issuetype: { name: settings.issueType },
                },
            }),
        });

        if (!response.ok) {
            const errorBody = await response.text();
            return { success: false, message: `Jira API error (${response.status}): ${errorBody}` };
        }

        const data = (await response.json()) as { key: string };
        return {
            success: true,
            issueKey: data.key,
            issueUrl: `${baseUrl}/browse/${data.key}`,
            message: `Issue ${data.key} created successfully!`,
        };
    } catch (error: any) {
        return { success: false, message: `Failed to create Jira issue: ${error.message}` };
    }
}

export async function attachFileToJiraIssue(
    settings: JiraSettings,
    issueKey: string,
    filePaths: string[]
): Promise<{ success: boolean; message: string }> {
    const baseUrl = normalizeJiraUrl(settings.jiraUrl);
    const auth = getAuthHeader(settings.jiraEmail, settings.jiraApiKey);

    try {
        for (const filePath of filePaths) {
            const fileName = path.basename(filePath);
            const fileBuffer = fs.readFileSync(filePath);

            // Create multipart form data manually
            const boundary = '----FormBoundary' + Date.now().toString(36);
            const bodyParts: Buffer[] = [];

            bodyParts.push(Buffer.from(
                `--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="${fileName}"\r\nContent-Type: application/octet-stream\r\n\r\n`
            ));
            bodyParts.push(fileBuffer);
            bodyParts.push(Buffer.from(`\r\n--${boundary}--\r\n`));

            const body = Buffer.concat(bodyParts);

            const response = await fetch(`${baseUrl}/rest/api/2/issue/${issueKey}/attachments`, {
                method: 'POST',
                headers: {
                    'Authorization': auth,
                    'X-Atlassian-Token': 'no-check',
                    'Content-Type': `multipart/form-data; boundary=${boundary}`,
                },
                body: body,
            });

            if (!response.ok) {
                const errorBody = await response.text();
                return { success: false, message: `Failed to attach ${fileName}: ${errorBody}` };
            }
        }

        return { success: true, message: 'All files attached successfully!' };
    } catch (error: any) {
        return { success: false, message: `Failed to attach files: ${error.message}` };
    }
}

export async function testJiraConnection(
    email: string,
    apiToken: string,
    jiraUrl: string
): Promise<{ success: boolean; message: string }> {
    const baseUrl = normalizeJiraUrl(jiraUrl);
    const auth = getAuthHeader(email, apiToken);

    try {
        const response = await fetch(`${baseUrl}/rest/api/2/myself`, {
            method: 'GET',
            headers: {
                'Authorization': auth,
                'Accept': 'application/json',
            },
        });

        if (!response.ok) {
            return { success: false, message: `Jira connection failed (${response.status}): ${await response.text()}` };
        }

        const data = (await response.json()) as { displayName: string };
        return { success: true, message: `Connected as ${data.displayName}` };
    } catch (error: any) {
        return { success: false, message: `Jira connection failed: ${error.message}` };
    }
}
